export const AUDIO = {
  FREQUENCY_HZ: 880,
  BEEP_DURATION_S: 0.35,
  ALARM_INTERVAL_MS: 600,
  GAIN_PEAK: 0.3,
  GAIN_ATTACK_S: 0.01,
  GAIN_TAIL_S: 0.02,
} as const;

export const ANIMATION = {
  DICE_ROLL_MS: 450,
  DICE_ROLL_DEFAULT_MS: 900,
  DICE_ROLL_MIN_MS: 200,
  DICE_ROLL_MAX_MS: 2500,
  DICE_CYCLE_INTERVAL_MS: 60,
  HINT_HIGHLIGHT_MS: 1200,
  CONFETTI_MS: 1800,
  LONG_PRESS_MS: 700,
  ARIA_LIVE_DEBOUNCE_MS: 50,
  MEMORY_PEEK_MS: 800,
  SIMON_FLASH_MS: 600,
  SIMON_GAP_MS: 150,
  SIMON_PRESS_MS: 200,
} as const;

export const HAPTICS = {
  DICE_TAP: 20,
  ALARM_PATTERN: [200, 100, 200, 100, 600],
} as const;

export const STORAGE_KEYS = {
  RING_DIFFICULTY: 'minispiele.ringSort.difficulty',
  RING_MIX: 'minispiele.ringSort.allowColorMix',
  RING_HIGHSCORES: 'minispiele.ringSort.highscores.v1',
  DICE_STATE: 'minispiele.dice.state.v1',
  DICE_MODIFIER: 'minispiele.dice.modifier.v1',
  DICE_HISTORY: 'minispiele.dice.history.v1',
  DICE_ROLL_DURATION: 'minispiele.dice.rollDurationMs.v1',
  TIMER_DURATION: 'minispiele.timer.durationSeconds',
  TIMER_PRESETS: 'minispiele.timer.userPresets.v1',
  TIMER_DISPLAY_MODE: 'minispiele.timer.displayMode.v1',
  MEMORY_DIFFICULTY: 'minispiele.memory.difficulty.v1',
  MEMORY_HIGHSCORES: 'minispiele.memory.highscores.v1',
  TFE_STATE: 'minispiele.tfe.state.v1',
  TFE_BEST: 'minispiele.tfe.bestScore.v1',
  SLIDING_DIFFICULTY: 'minispiele.sliding.difficulty.v1',
  SLIDING_HIGHSCORES: 'minispiele.sliding.highscores.v1',
  SIMON_BEST: 'minispiele.simon.bestLevel.v1',
  MINES_DIFFICULTY: 'minispiele.mines.difficulty.v1',
  MINES_HIGHSCORES: 'minispiele.mines.highscores.v1',
  SNAKE_BEST: 'minispiele.snake.bestScore.v1',
  WORDLE_STATS: 'minispiele.wordle.stats.v1',
  REACTION_BEST: 'minispiele.reaction.bestMs.v1',
  STROOP_BEST: 'minispiele.stroop.bestScore.v1',
  SCHULTE_SIZE: 'minispiele.schulte.size.v1',
  SCHULTE_BEST: 'minispiele.schulte.bestSeconds.v1',
  HANOI_DISKS: 'minispiele.hanoi.disks.v1',
  HANOI_BEST: 'minispiele.hanoi.bestMoves.v1',
  LIGHTS_BEST: 'minispiele.lights.bestMoves.v1',
  MASTERMIND_BEST: 'minispiele.mastermind.bestGuesses.v1',
  HANGMAN_STATS: 'minispiele.hangman.stats.v1',
  ANAGRAM_BEST: 'minispiele.anagram.bestStreak.v1',
  SUDOKU_DIFFICULTY: 'minispiele.sudoku.difficulty.v1',
  SUDOKU_STATE: 'minispiele.sudoku.state.v1',
  SUDOKU_BEST: 'minispiele.sudoku.best.v1',
  NONOGRAM_SIZE: 'minispiele.nonogram.size.v1',
  NONOGRAM_BEST: 'minispiele.nonogram.best.v1',
  SOKOBAN_LEVEL: 'minispiele.sokoban.level.v1',
  SOKOBAN_BEST: 'minispiele.sokoban.best.v1',
  WORDSEARCH_BEST: 'minispiele.wordsearch.bestSeconds.v1',
  BREAKOUT_BEST: 'minispiele.breakout.bestScore.v1',
  BUBBLES_BEST: 'minispiele.bubbles.bestScore.v1',
  BLOCKS_BEST: 'minispiele.blocks.bestScore.v1',
  FREECELL_BEST: 'minispiele.freecell.bestMoves.v1',
  TANGRAM_LEVEL: 'minispiele.tangram.level.v1',
  FLOW_BEST: 'minispiele.flow.best.v1',
  GFRETT_LEVEL: 'minispiele.gfrett.level.v1',
  GFRETT_BEST: 'minispiele.gfrett.best.v1',
  HOME_CATEGORY_FILTER: 'minispiele.home.categoryFilter.v1',
  RECENT_GAMES: 'minispiele.recent.v1',
  FAVORITES: 'minispiele.favorites.v1',
  SETTINGS: 'minispiele.settings.v1',
} as const;
